services:
  my-server:
    build:
      context: .
      dockerfile: Dockerfile.dev # Docker File로 만들어진 이미지로 띄운다
    ports:
      - 8080:8080
    depends_on: # 서비스가 먼저 띄워진 후 다음 서비스 실행
      my-db:
        condition: service_healthy # 헬스체크 했을 때 mysql이 잘 작동되는지 확인 확인이 되면 spring boot 실행
      my-cache-server:
        condition: service_healthy # redis 헬스체크

  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  my-cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10