spring:
  profiles:
    default: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.cache: trace

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://redis-sample-db.cyr8sbmjsowa.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  # 하위 내용에 대해 작성하지 않아도 기본적으로 copy 된다.